const Sdata = [
  {
    headings: "Lean six sigma green belt",
    vir: "virtual",
    para: "best selling six sigma virtual courses",
    image: "",
    dat: "19",
    day: "Mon",
    mon: "June",
    year: "2023",
    rupees: "£1995",
    value: "£1495",
    enquiry: "Enquire",
    enqimage: "",
    timing: "Duration:",
    days: "5 days",
    view: "View more dates",
    gimage: " ",
    callimage: "",
    book: "Book now",
  },
  {
    month: "next month",
    headings: "Lean six sigma green belt",
    vir: "virtual",
    para: "best selling six sigma virtual courses",
    image: "",
    dat: "19",
    day: "Mon",
    mon: "June",
    year: "2024",
    rupees: "£2025",
    value: "£2026",
    enquiry: "Enquire",
    enqimage: "",
    timing: "Duration:",
    days: "5 days",
    view: "View more dates",
    gimage: " ",
    callimage: "",
    book: "Book now",
  },
  {
    month: "next month",
    heading: "Lean six sigma green belt",
    vir: "virtual",
    para: "best selling six sigma virtual courses",
    image: "",
    dat: "19",
    day: "Mon",
    mon: "June",
    year: "2025",
    rupees: "£1995",
    value: "£1495",
    enquiry: "Enquire",
    enqimage: "",
    timing: "Duration:",
    days: "5 days",
    view: "View more dates",
    gimage: " ",
    callimage: "",
    book: "Book now",
  },
  {
    month: "next month",
    heading: "Lean six sigma green belt",
    vir: "virtual",
    para: "best selling six sigma virtual courses",
    image: "",
    dat: "19",
    day: "Mon",
    mon: "June",
    year: "2026",
    rupees: "£1995",
    value: "£1495",
    enquiry: "Enquire",
    enqimage: "",
    timing: "Duration:",
    days: "5 days",
    view: "View more dates",
    gimage: " ",
    callimage: "",
    book: "Book now",
  },
  {
    month: "next month",
    heading: "Lean six sigma green belt",
    vir: "virtual",
    para: "best selling six sigma virtual courses",
    image: "",
    dat: "19",
    day: "Mon",
    mon: "June",
    year: "2027",
    rupees: "£1995",
    value: "£1495",
    enquiry: "Enquire",
    enqimage: "",
    timing: "Duration:",
    days: "5 days",
    view: "View more dates",
    gimage: " ",
    callimage: "",
    book: "Book now",
  },
  {
    month: "next month",
    heading: "Lean six sigma green belt",
    vir: "virtual",
    para: "best selling six sigma virtual courses",
    image: "",
    dat: "19",
    day: "Mon",
    mon: "June",
    year: "2028",
    rupees: "£1995",
    value: "£1495",
    enquiry: "Enquire",
    enqimage: "",
    timing: "Duration:",
    days: "5 days",
    view: "View more dates",
    gimage: " ",
    callimage: "",
    book: "Book now",
  },
  {
    month: "next month",
    heading: "Lean six sigma green belt",
    vir: "virtual",
    para: "best selling six sigma virtual courses",
    image: "",
    dat: "19",
    day: "Mon",
    mon: "June",
    year: "2029",
    rupees: "£1995",
    value: "£1495",
    enquiry: "Enquire",
    enqimage: "",
    timing: "Duration:",
    days: "5 days",
    view: "View more dates",
    gimage: " ",
    callimage: "",
    book: "Book now",
  },
  {
    month: "next month",
    heading: "Lean six sigma green belt",
    vir: "virtual",
    para: "best selling six sigma virtual courses",
    image: "",
    dat: "19",
    day: "Mon",
    mon: "June",
    year: "2030",
    rupees: "£1995",
    value: "£1495",
    enquiry: "Enquire",
    enqimage: "",
    timing: "Duration:",
    days: "5 days",
    view: "View more dates",
    gimage: " ",
    callimage: "",
    book: "Book now",
  },
  {
    month: "next month",
    heading: "Lean six sigma green belt",
    vir: "virtual",
    para: "best selling six sigma virtual courses",
    image: "",
    dat: "19",
    day: "Mon",
    mon: "June",
    year: "2031",
    rupees: "£1995",
    value: "£1495",
    enquiry: "Enquire",
    enqimage: "",
    timing: "Duration:",
    days: "5 days",
    view: "View more dates",
    gimage: " ",
    callimage: "",
    book: "Book now",
  },
  {
    month: "next month",
    heading: "Lean six sigma green belt",
    vir: "virtual",
    para: "best selling six sigma virtual courses",
    image: "",
    dat: "19",
    day: "Mon",
    mon: "June",
    year: "2032",
    rupees: "£1995",
    value: "£1495",
    enquiry: "Enquire",
    enqimage: "",
    timing: "Duration:",
    days: "5 days",
    view: "View more dates",
    gimage: " ",
    callimage: "",
    book: "Book now",
  },
  {
    month: "next month",
    heading: "Lean six sigma green belt",
    vir: "virtual",
    para: "best selling six sigma virtual courses",
    image: "",
    dat: "19",
    day: "Mon",
    mon: "June",
    year: "2033",
    rupees: "£1995",
    value: "£1495",
    enquiry: "Enquire",
    enqimage: "",
    timing: "Duration:",
    days: "5 days",
    view: "View more dates",
    gimage: " ",
    callimage: "",
    book: "Book now",
  },
  {
    month: "next month",
    heading: "Lean six sigma green belt",
    vir: "virtual",
    para: "best selling six sigma virtual courses",
    image: "",
    dat: "19",
    day: "Mon",
    mon: "June",
    year: "2034",
    rupees: "£1995",
    value: "£1495",
    enquiry: "Enquire",
    enqimage: "",
    timing: "Duration:",
    days: "5 days",
    view: "View more dates",
    gimage: " ",
    callimage: "",
    book: "Book now",
  },
  {
    month: "next month",
    heading: "Lean six sigma green belt",
    vir: "virtual",
    para: "best selling six sigma virtual courses",
    image: "",
    dat: "19",
    day: "Mon",
    mon: "June",
    year: "2035",
    rupees: "£1995",
    value: "£1495",
    enquiry: "Enquire",
    enqimage: "",
    timing: "Duration:",
    days: "5 days",
    view: "View more dates",
    gimage: " ",
    callimage: "",
    book: "Book now",
  },
  {
    month: "next month",
    heading: "Lean six sigma green belt",
    vir: "virtual",
    para: "best selling six sigma virtual courses",
    image: "",
    dat: "19",
    day: "Mon",
    mon: "June",
    year: "2036",
    rupees: "£1995",
    value: "£1495",
    enquiry: "Enquire",
    enqimage: "",
    timing: "Duration:",
    days: "5 days",
    view: "View more dates",
    gimage: " ",
    callimage: "",
    book: "Book now",
  },
  {
    month: "next month",
    heading: "Lean six sigma green belt",
    vir: "virtual",
    para: "best selling six sigma virtual courses",
    image: "",
    dat: "19",
    day: "Mon",
    mon: "June",
    year: "2037",
    rupees: "£1995",
    value: "£1495",
    enquiry: "Enquire",
    enqimage: "",
    timing: "Duration:",
    days: "5 days",
    view: "View more dates",
    gimage: " ",
    callimage: "",
    book: "Book now",
  },
  {
    month: "next month",
    heading: "Lean six sigma green belt",
    vir: "virtual",
    para: "best selling six sigma virtual courses",
    image: "",
    dat: "19",
    day: "Mon",
    mon: "June",
    year: "2038",
    rupees: "£1995",
    value: "£1495",
    enquiry: "Enquire",
    enqimage: "",
    timing: "Duration:",
    days: "5 days",
    view: "View more dates",
    gimage: " ",
    callimage: "",
    book: "Book now",
  },
  {
    month: "next month",
    heading: "Lean six sigma green belt",
    vir: "virtual",
    para: "best selling six sigma virtual courses",
    image: "",
    dat: "19",
    day: "Mon",
    mon: "June",
    year: "2039",
    rupees: "£1995",
    value: "£1495",
    enquiry: "Enquire",
    enqimage: "",
    timing: "Duration:",
    days: "5 days",
    view: "View more dates",
    gimage: " ",
    callimage: "",
    book: "Book now",
  },
  {
    month: "next month",
    heading: "Lean six sigma green belt",
    vir: "virtual",
    para: "best selling six sigma virtual courses",
    image: "",
    dat: "19",
    day: "Mon",
    mon: "June",
    year: "2040",
    rupees: "£1995",
    value: "£1495",
    enquiry: "Enquire",
    enqimage: "",
    timing: "Duration:",
    days: "5 days",
    view: "View more dates",
    gimage: " ",
    callimage: "",
    book: "Book now",
  },
  {
    month: "next month",
    heading: "Lean six sigma green belt",
    vir: "virtual",
    para: "best selling six sigma virtual courses",
    image: "",
    dat: "19",
    day: "Mon",
    mon: "June",
    year: "2041",
    rupees: "£1995",
    value: "£1495",
    enquiry: "Enquire",
    enqimage: "",
    timing: "Duration:",
    days: "5 days",
    view: "View more dates",
    gimage: " ",
    callimage: "",
    book: "Book now",
  },
];
export default Sdata;
